# Generated by Django 5.0.4 on 2024-05-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_alter_userprofile_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
