import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";
//import Link from "next/link";

import Navbar from "@/components/navbar";
//import LoginPage from "../components/login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



// This is the height of the navbar which will also be used to set the padding-top of the main content
// NOTE: you should modify this value to match the height of the navbar
const navbarHeight: string = "50px";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={'1040494859138-vji3ddfil5jancg23ifaginvmn71hktf.apps.googleusercontent.com'}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar height={navbarHeight} />
          <div style={{ paddingTop: navbarHeight }}>
            {children}
          </div>

        </body>

      </html>
    </GoogleOAuthProvider>
  );
}
